//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models.DataBaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Image1 = new FileEntity();
            this.Image2 = new FileEntity();
            this.Image3 = new FileEntity();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LogDescription { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public bool InCar { get; set; }
        public Nullable<int> SellingId { get; set; }
        public Nullable<int> ByingId { get; set; }
    
        public FileEntity Image1 { get; set; }
        public FileEntity Image2 { get; set; }
        public FileEntity Image3 { get; set; }
    
        public virtual User SellingUser { get; set; }
        public virtual User ByingUser { get; set; }
    }
}
